Progress

diff --git a/.github/workflows/api-secret-test.yml b/.github/workflows/api-secret-test.yml
--- a/.github/workflows/api-secret-test.yml
+++ b/.github/workflows/api-secret-test.yml
@@ -32,8 +32,11 @@ jobs:
     steps:    
     - name: Check Environment Variables
       run: |
-        if [[ -z "${{ env.cx_version_benchmark_url }}" ]] || [[ -z "${{ secrets.cx_version_benchmark_api_key }}" ]]; then
-            echo "Error: Environment variables cx_version_benchmark_url or cx_version_benchmark_api_key are not set."
+        if [[ -z "${{ inputs.cx_version_benchmark_url }}" ]]; then 
+            echo "EROOR: Environment variable [[ cx_version_benchmark_url ]]"
+            exit 44
+        elif [[ -z "${{ secrets.cx_version_benchmark_api_key }}" ]]; then
+            echo "ERROR: Secret [[ cx_version_benchmark_api_key ]] is not set."
             exit 55
         fi
 
@@ -62,14 +65,13 @@ jobs:
         run: |
           response=$(curl -s -o response.txt -w "%{http_code}" \
           --location \
-          --request POST "${{ env.cx_version_benchmark_url }}" \
-          --header "Authorization: Bearer ${{ secrets.cx_version_benchmark_api_key }}" \
+          --request POST "${{ inputs.cx_version_benchmark_url }}" \
           --header "Content-Type: application/json" \
           --data-raw '{
             "name": "${{ env.SANITIZED_NAME }}",
             "application": ["${{ env.SANITIZED_APPLICATION }}"],
             "subsystem": ["${{ env.SANITIZED_SUBSYSTEM }}"],
-            "key": ["${{ secrets.cx_version_benchmark_api_key}}"]
+            "key": ["${{ secrets.cx_version_benchmark_api_key }}"]
           }')
 
           if [[ "$response" -ne 200 ]]; then
